name: Keep Backend Alive

on:
  schedule:
    - cron: '*/14 * * * *' # Toutes les 14 minutes
  workflow_dispatch: # Permet de le lancer manuellement si besoin

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: |
          curl -I https://prout-backend.onrender.com/
          echo "Ping sent to keep server awake!"

